version: '3.8'

services:
    postgres:
        image: postgres:10.5
        container_name: checkwho-postgres
        restart: always
        ports: 
            - "5433:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: checkwho_dev
        # persist postgres data even after teardown of image
        volumes:
            - postgres_data:/var/lib/postgres/

    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
        target: dev
      environment:
        DB_NAME: checkwho_dev
        DB_HOST: postgres
        DB_USERNAME: root
        DB_PASSWORD: root
      env_file:
        - ./backend/.env
      depends_on:
        - postgres
      ports:
        - "8080:8080"
      container_name: checkwho-backend
      command: npm run dev
      # used to set up hot-reloading in docker
      volumes:
        - ./backend/:/usr/src
        - /usr/src/node_modules

    frontend-govt:
      build:
        context: ./frontend-govt
        dockerfile: Dockerfile
      ports:
        - "3001:3000"
      container_name: checkwho-frontend-govt
      command: npm run dev
      depends_on:
        - backend
      # used to set up hot-reloading in docker
      volumes:
        - ./frontend-govt:/usr/src
        - /usr/src/node_modules
            
# persist postgres data even after teardown of image
volumes:
  postgres_data:
