version: '3.8'

services:
    postgres:
        image: postgres:10.5
        container_name: verifysg-postgres
        restart: always
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: verifysg_dev
        # persist postgres data even after teardown of image
        volumes:
            - postgres_data:/var/lib/postgres/
            
# persist postgres data even after teardown of image
volumes:
  postgres_data: