version: '3.8'

services:
    postgres:
        image: postgres:10.5
        container_name: verifysg-postgres
        restart: always
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: verifysg_dev
        # persist postgres data even after teardown of image
        volumes:
            - postgres_data:/var/lib/postgres/

    pgadmin:
        image: dpage/pgadmin4:6
        container_name: verifysg-pg_admin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 5050
        ports:
            - "5050:5050"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: dev
        environment:
            DB_NAME: verifysg_dev
            DB_HOST: postgres
            DB_USERNAME: root
            DB_PASSWORD: root
        env_file:
            - ./backend/.env
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        container_name: verifysg-backend
        command: npm run dev
        # used to set up hot-reloading in docker
        volumes:
            - ./backend/:/usr/src
            - /usr/src/node_modules

    frontend-public:
        build:
            context: ./frontend-public
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        container_name: verifysg-frontend-public
        command: npm run dev
        # used to set up hot-reloading in docker
        volumes: 
            - ./frontend-public:/usr/src
            - /usr/src/node_modules

    frontend-govt:
        build:
            context: ./frontend-govt
            dockerfile: Dockerfile
        ports:
            - "3001:3000"
        container_name: verifysg-frontend-govt
        command: npm run dev
        # used to set up hot-reloading in docker
        volumes: 
            - ./frontend-govt:/usr/src
            - /usr/src/node_modules
# persist postgres data even after teardown of image
volumes:
  postgres_data: