name: Deploy app and run e2e test
on:
  push:
    branches:
      - master

concurrency: deploy-app-${{ github.ref }}

jobs:
  ci:
    name: Run CI (lint and test)
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  deploy-eb:
    name: Deploy frontend and backend to AWS Elastic Beanstalk
    needs: ci
    uses: ./.github/workflows/deploy-eb.yml
    secrets: inherit
  e2e:
    name: End-to-end tests
    needs: deploy-eb
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
